package Pojo;
 


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer id;
     private Users usersByKimden;
     private Users usersByKime;
     private String mesaj;
     private boolean okundu;
     private Date zaman;

    public Message() {
    }

    public Message(Users usersByKimden, Users usersByKime, String mesaj, boolean okundu, Date zaman) {
       this.usersByKimden = usersByKimden;
       this.usersByKime = usersByKime;
       this.mesaj = mesaj;
       this.okundu = okundu;
       this.zaman = zaman;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsersByKimden() {
        return this.usersByKimden;
    }
    
    public void setUsersByKimden(Users usersByKimden) {
        this.usersByKimden = usersByKimden;
    }
    public Users getUsersByKime() {
        return this.usersByKime;
    }
    
    public void setUsersByKime(Users usersByKime) {
        this.usersByKime = usersByKime;
    }
    public String getMesaj() {
        return this.mesaj;
    }
    
    public void setMesaj(String mesaj) {
        this.mesaj = mesaj;
    }
    public boolean isOkundu() {
        return this.okundu;
    }
    
    public void setOkundu(boolean okundu) {
        this.okundu = okundu;
    }
    public Date getZaman() {
        return this.zaman;
    }
    
    public void setZaman(Date zaman) {
        this.zaman = zaman;
    }




}


